import numpy as np
import pandas as pd
import scipy.stats



rewardSetting = [
                [0.2, 0.4, 0.6, 0.8],
                [1/7, 2/7, 3/7, 4/7, 5/7, 6/7],
                [1/8, 2/8, 3/8, 4/8, 5/8, 6/8, 7/8],
                [1/8, 2/8, 3/8, 4/8, 5/8, 6/8, 7/8]
                ] 

hypotheses_3D = [
    # #1d relevant
    [[1, np.nan ,np.nan],[np.nan, np.nan, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, 1 ,np.nan],[np.nan, np.nan, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],

    # # 2d relevant
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan]],

    [[1, np.nan, np.nan],[np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],

    [[np.nan, np.nan, np.nan],[1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, np.nan],[np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, 1]], 
    

    # # #3d relevant
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, 1]],

    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, 1]],

    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, 1]],

    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, 1]],

    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, 1]],

    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, 1]],

    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [np.nan, np.nan, 1]],

    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [np.nan, np.nan, 1]],

    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [np.nan,np.nan, 1 ]]
]

hypotheses_test = [
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan,np.nan, 1 ]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, 1]]
]
# hypotheses space for 3d
hypotheses_4D = [
    #1d relevant
    [[1, np.nan ,np.nan],[np.nan, np.nan, np.nan], [np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, 1 ,np.nan],[np.nan, np.nan, np.nan], [np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, np.nan], [np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [1, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, 1, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, np.nan, 1],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],

    # 2d relevant
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan]],

    [[1, np.nan, np.nan],[np.nan, np.nan, np.nan], [1, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, 1, np.nan],[np.nan, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, np.nan, 1],[np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, np.nan], [1, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, np.nan], [np.nan, 1, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, np.nan], [np.nan, np.nan, 1],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, np.nan], [1, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, np.nan], [np.nan, 1, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, np.nan], [np.nan, np.nan, 1],[np.nan, np.nan, np.nan]],

    [[1, np.nan, np.nan],[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],

    [[np.nan, np.nan, np.nan],[1, np.nan, np.nan], [1, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, 1, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, 1],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, 1, np.nan], [1, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, 1, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, 1],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, 1], [1, np.nan, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, 1, np.nan],[np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, 1],[np.nan, np.nan, np.nan]], 

    [[np.nan, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1]], 

    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [1, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, 1, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan],[np.nan, np.nan, np.nan], [np.nan, np.nan, 1], [np.nan, np.nan, 1]], 

    #3d relevant
    # 1 part
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [1, np.nan, np.nan], [np.nan, np.nan, np.nan]],
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, 1, np.nan], [np.nan, np.nan, np.nan]],
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, 1], [np.nan, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [1, np.nan, np.nan], [np.nan, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, 1, np.nan], [np.nan, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, 1], [np.nan, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [1, np.nan, np.nan], [np.nan, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, 1, np.nan], [np.nan, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, 1], [np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [1, np.nan, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [np.nan, 1, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, 1], [np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [1, np.nan, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [np.nan, 1, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, 1], [np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [1, np.nan, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [np.nan, 1, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, 1], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [1, np.nan, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [np.nan, 1, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [np.nan, np.nan, 1], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [1, np.nan, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [np.nan, 1, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [np.nan, np.nan, 1], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [1, np.nan, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [np.nan, 1, np.nan], [np.nan, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [np.nan, 1, np.nan], [np.nan, np.nan, np.nan]],

    # 2 part

    [[1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan]],

    # 3 part

    [[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [1, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan], [np.nan, np.nan, 1]],
    [[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1], [np.nan, np.nan, 1]],
    [[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [1, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [1, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [np.nan, 1, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1], [np.nan, np.nan, np.nan], [np.nan, np.nan, 1], [np.nan, 1, np.nan]],

    # 4 part

    [[np.nan, np.nan, np.nan], [1, np.nan, np.nan],[1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan], [1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan], [1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, np.nan], [1, np.nan, np.nan],[np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan], [1, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan], [1, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, np.nan], [1, np.nan, np.nan],[np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan], [1, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan], [1, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, np.nan], [np.nan, 1, np.nan],[1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan], [np.nan, 1, np.nan],[1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan], [np.nan, 1, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, np.nan], [np.nan, 1, np.nan],[np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan], [np.nan, 1, np.nan],[np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan], [np.nan, 1, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, np.nan], [np.nan, 1, np.nan],[np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan], [np.nan, 1, np.nan],[np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan], [np.nan, 1, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, np.nan], [np.nan, np.nan, 1],[1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan], [np.nan, np.nan, 1],[1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan], [np.nan, np.nan, 1],[1, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, np.nan], [np.nan, np.nan, 1],[np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan], [np.nan, np.nan, 1],[np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan], [np.nan, np.nan, 1],[np.nan, 1, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, np.nan], [np.nan, np.nan, 1],[np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[np.nan, np.nan, np.nan], [np.nan, np.nan, 1],[np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, np.nan], [np.nan, np.nan, 1],[np.nan, np.nan, 1], [np.nan, 1, np.nan]],

    # 4d relevant
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [np.nan, np.nan, 1], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [1, np.nan, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [np.nan, 1, np.nan], [1, np.nan, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [np.nan,np.nan, 1 ], [1, np.nan, np.nan]],

    [[1, np.nan, np.nan],[1, np.nan, np.nan], [1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [np.nan, np.nan, 1], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [1, np.nan, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [np.nan, 1, np.nan], [np.nan, 1, np.nan]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [np.nan,np.nan, 1 ], [np.nan, 1, np.nan]],

    [[1, np.nan, np.nan],[1, np.nan, np.nan], [1, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, 1, np.nan], [np.nan, np.nan, 1]],
    [[1, np.nan, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, 1], [np.nan, np.nan, 1]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [1, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, 1, np.nan], [np.nan, np.nan, 1]],
    [[1, np.nan, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, 1], [np.nan, np.nan, 1]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [1, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, 1, np.nan], [np.nan, np.nan, 1]],
    [[1, np.nan, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, 1], [np.nan, np.nan, 1]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [1, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [np.nan, 1, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, 1, np.nan],[1, np.nan, np.nan], [np.nan, np.nan, 1], [np.nan, np.nan, 1]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [1, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [np.nan, 1, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, 1, np.nan],[np.nan, 1, np.nan], [np.nan, np.nan, 1], [np.nan, np.nan, 1]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [1, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [np.nan, 1, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, 1, np.nan],[np.nan, np.nan, 1], [np.nan, np.nan, 1], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [1, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [np.nan, 1, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, 1],[1, np.nan, np.nan], [np.nan, np.nan, 1], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [1, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [np.nan, 1, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, 1],[np.nan, 1, np.nan], [np.nan, np.nan, 1], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [1, np.nan, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [np.nan, 1, np.nan], [np.nan, np.nan, 1]],
    [[np.nan, np.nan, 1],[np.nan, np.nan, 1], [np.nan,np.nan, 1 ], [np.nan, np.nan, 1]]
]
